version: '3.8'
services:
  mysql:
    build: mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  app:
    depends_on:
      - mysql
    build: node/
    ports:
      - "3000:3000"
    environment:
      - PORT=3000


